/**
 * Penrose Tiling — aperiodic tiling via subdivision.
 * Fills the plane with a pattern that NEVER repeats. 5-fold symmetry.
 * Generated by recursive subdivision using golden ratio rules.
 */

import { Algorithm } from '../base.js';

const PHI = (1 + Math.sqrt(5)) / 2;

// Triangle types for P3 (kite/dart decomposition via half-tiles)
const THIN = 0;
const THICK = 1;

function subdivide(triangles) {
  const result = [];
  for (const tri of triangles) {
    const [type, ax, ay, bx, by, cx, cy] = tri;
    if (type === THIN) {
      // Subdivide thin triangle (half-dart)
      const px = ax + (bx - ax) / PHI;
      const py = ay + (by - ay) / PHI;
      result.push([THIN, cx, cy, px, py, bx, by]);
      result.push([THICK, px, py, cx, cy, ax, ay]);
    } else {
      // Subdivide thick triangle (half-kite)
      const qx = bx + (ax - bx) / PHI;
      const qy = by + (ay - by) / PHI;
      const rx = bx + (cx - bx) / PHI;
      const ry = by + (cy - by) / PHI;
      result.push([THICK, qx, qy, ax, ay, rx, ry]);
      result.push([THICK, rx, ry, cx, cy, ax, ay]);
      result.push([THIN, rx, ry, qx, qy, bx, by]);
    }
  }
  return result;
}

export class Penrose extends Algorithm {
  get metadata() {
    return {
      name: 'Penrose Tiling',
      eq: 'aperiodic subdivision with phi',
      cat: 'Data Art',
      desc: 'Aperiodic tiling that fills the plane but never repeats. 5-fold symmetry found in quasicrystals. Generated by recursive golden ratio subdivision.',
    };
  }

  get params() {
    return [
      { id: 'pen_depth', label: 'Depth',  min: 3, max: 8,   step: 1   },
      { id: 'pen_scale', label: 'Scale',  min: 0.5, max: 3, step: 0.1 },
      { id: 'pen_type',  label: 'Type',   min: 0, max: 1,   step: 1   },
    ];
  }

  get detailParam() {
    return { id: 'pen_depth', min: 3, max: 8, step: 1 };
  }

  get cursorMap() {
    return (mx, _my, s) => {
      s.pen_scale = 0.5 + mx * 2.5;
    };
  }

  animate(s) {
    // Subtle rotation over time
  }

  render(ctx, W, H, s) {
    const depth = Math.max(3, Math.min(8, Math.round(s.pen_depth || 5)));
    const scale = Math.max(0.5, Math.min(3, s.pen_scale || 1.5));
    const type = Math.round(s.pen_type || 0);
    const fg = this.engine.fg(s);
    const t = (s.time || 0) * 0.05;

    const cx = W / 2;
    const cy = H / 2;
    const radius = Math.min(W, H) * 0.5 * scale;

    // Build initial star of triangles (10 slices)
    let triangles = [];
    for (let i = 0; i < 10; i++) {
      const a0 = (2 * Math.PI * i / 10) + t;
      const a1 = (2 * Math.PI * (i + 1) / 10) + t;
      const bx = cx + radius * Math.cos(a0);
      const by = cy + radius * Math.sin(a0);
      const cxp = cx + radius * Math.cos(a1);
      const cyp = cy + radius * Math.sin(a1);

      if (i % 2 === 0) {
        triangles.push([THICK, cx, cy, bx, by, cxp, cyp]);
      } else {
        triangles.push([THICK, cx, cy, cxp, cyp, bx, by]);
      }
    }

    // Subdivide
    for (let d = 0; d < depth; d++) {
      triangles = subdivide(triangles);
    }

    // Draw
    ctx.strokeStyle = fg;
    ctx.lineWidth = 0.6;
    ctx.globalAlpha = 0.7;

    if (type === 0) {
      // Wireframe
      ctx.beginPath();
      for (const tri of triangles) {
        const [, ax, ay, bx, by, cxp, cyp] = tri;
        ctx.moveTo(ax, ay);
        ctx.lineTo(bx, by);
        ctx.lineTo(cxp, cyp);
        ctx.closePath();
      }
      ctx.stroke();
    } else {
      // Filled with alternating shades
      for (const tri of triangles) {
        const [ttype, ax, ay, bx, by, cxp, cyp] = tri;
        ctx.globalAlpha = ttype === THICK ? 0.15 : 0.05;
        ctx.fillStyle = fg;
        ctx.beginPath();
        ctx.moveTo(ax, ay);
        ctx.lineTo(bx, by);
        ctx.lineTo(cxp, cyp);
        ctx.closePath();
        ctx.fill();
      }
      ctx.globalAlpha = 0.5;
      ctx.beginPath();
      for (const tri of triangles) {
        const [, ax, ay, bx, by, cxp, cyp] = tri;
        ctx.moveTo(ax, ay);
        ctx.lineTo(bx, by);
        ctx.lineTo(cxp, cyp);
        ctx.closePath();
      }
      ctx.stroke();
    }

    ctx.globalAlpha = 1;
  }
}
