/**
 * Rorschach — FBM noise field thresholded and mirrored on Y axis.
 * Symmetric organic growth patterns — ink blot tests generated by algorithms.
 */

import { Algorithm } from '../base.js';
import { createProgram } from '../../webgl/context.js';
import { Quad } from '../../webgl/quad.js';
import { NOISE_2D } from '../../webgl/shader-lib.js';

// ── Shaders ───────────────────────────────────────────────────────────────────

const VERT_SRC = /* glsl */`
attribute vec2 a_position;
varying vec2 v_uv;
void main() {
  v_uv = a_position * 0.5 + 0.5;
  gl_Position = vec4(a_position, 0.0, 1.0);
}
`;

const FRAG_SRC = /* glsl */`
precision highp float;

varying vec2 v_uv;

uniform float u_time;
uniform float u_scale;
uniform float u_threshold;
uniform int   u_detail;
uniform int   u_colorMode;
uniform bool  u_transparent;

${NOISE_2D}

// Variable-octave FBM (driven by u_detail uniform)
float fbmN(vec2 p, int octaves) {
  float value = 0.0;
  float amplitude = 0.5;
  float frequency = 1.0;
  for (int i = 0; i < 6; i++) {
    if (i >= octaves) break;
    value += amplitude * snoise(p * frequency);
    amplitude *= 0.5;
    frequency *= 2.0;
  }
  return value;
}

void main() {
  // Mirror on Y axis — fold left half onto right
  vec2 uv = v_uv;
  uv.x = abs(uv.x - 0.5) + 0.5;  // right half is the canonical side

  // Sample noise with drift
  vec2 p = uv / u_scale + vec2(u_time * 0.15, u_time * 0.08);
  float n = fbmN(p, u_detail);

  // Map [-1,1] → [0,1]
  float v = n * 0.5 + 0.5;

  // Threshold
  float fg = step(u_threshold, v);

  // ── Colour mode ────────────────────────────────────────────────────────────
  vec3 col;
  if (u_colorMode == 0) {
    col = vec3(fg);
  } else if (u_colorMode == 1) {
    col = vec3(1.0 - fg);
  } else {
    col = mix(vec3(0.06, 0.06, 0.08), vec3(0.73, 0.73, 0.76), fg);
  }

  float alpha;
  if (u_transparent) {
    alpha = fg;
  } else {
    alpha = 1.0;
  }

  gl_FragColor = vec4(col * alpha, alpha);
}
`;

// ── Helpers ───────────────────────────────────────────────────────────────────

function colorModeIndex(mode) {
  if (mode === 'bw')     return 1;
  if (mode === 'silver') return 2;
  return 0;
}

// ── Class ─────────────────────────────────────────────────────────────────────

export class Rorschach extends Algorithm {
  constructor(engine) {
    super(engine);
    this._prog = null;
    this._quad = null;
    this._gl   = null;
  }

  get metadata() {
    return {
      name: 'Rorschach',
      eq:   'Noise + axis mirror',
      cat:  'Data Art',
      desc: 'Symmetric organic growth patterns — ink blot tests generated by algorithms.',
    };
  }

  get params() {
    return [
      { id: 'ror_scale',     label: 'Scale',     min: 0.005, max: 0.03, step: 0.001 },
      { id: 'ror_threshold', label: 'Threshold', min: 0.3,   max: 0.7,  step: 0.01  },
      { id: 'ror_detail',    label: 'Detail',    min: 1,     max: 6,    step: 1      },
    ];
  }

  get detailParam() {
    return { id: 'ror_detail', min: 1, max: 6, step: 1 };
  }

  get cursorMap() {
    return (mx, my, s) => {
      s.ror_threshold = 0.3 + mx * 0.4;
      s.ror_scale     = 0.005 + my * 0.025;
    };
  }

  animate(s) {
    // Drift handled in shader via s.time
  }

  render(ctx, W, H, s) {
    const glCanvas = this.engine.getGLCanvas();
    const gl       = this.engine.getGL();

    if (!gl) {
      ctx.fillStyle = '#000';
      ctx.fillRect(0, 0, W, H);
      ctx.fillStyle = '#fff';
      ctx.font = '16px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('WebGL not available', W / 2, H / 2);
      return;
    }

    if (!this._prog || this._gl !== gl) {
      this._gl   = gl;
      this._prog = createProgram(gl, VERT_SRC, FRAG_SRC);
      this._quad = new Quad(gl);
    }
    if (!this._prog) return;

    gl.viewport(0, 0, glCanvas.width, glCanvas.height);
    gl.clearColor(0, 0, 0, 0);
    gl.clear(gl.COLOR_BUFFER_BIT);
    gl.enable(gl.BLEND);
    gl.blendFunc(gl.ONE, gl.ONE_MINUS_SRC_ALPHA);

    const prog = this._prog;
    gl.useProgram(prog);

    const cmLoc = gl.getUniformLocation(prog, 'u_colorMode');
    const trLoc = gl.getUniformLocation(prog, 'u_transparent');
    const dtLoc = gl.getUniformLocation(prog, 'u_detail');
    if (cmLoc !== null) gl.uniform1i(cmLoc, colorModeIndex(s.colorMode));
    if (trLoc !== null) gl.uniform1i(trLoc, s.transparent ? 1 : 0);
    if (dtLoc !== null) gl.uniform1i(dtLoc, Math.round(s.ror_detail ?? 3));

    this._quad.render(gl, prog, {
      u_time:      s.time ?? 0,
      u_scale:     s.ror_scale     ?? 0.015,
      u_threshold: s.ror_threshold ?? 0.48,
    });

    ctx.drawImage(glCanvas, 0, 0, W, H);
  }

  collectSVG() { return null; }
}
